import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'forged-oil',
    name: 'Forged • Beard & Body Oil',
    benefit: 'Argan, Castor, Avocado & Babassu oils. Fast-absorbing. Non-greasy.',
    price: 37,
    image: 'https://www.zaddyproducts.com/cdn/shop/files/forge_new_bottle_1000x.jpg?v=1751427779',
    vertical: 'skin',
    tag: 'Skin · Essentials',
    description: 'In a world of hormone disruptors, ZADDY Forged Oil is built to protect your edge. Subscribe & Save available.',
  },
  {
    id: 'hydra-moisturizer',
    name: 'Hydra+ • Facial Moisturizer',
    benefit: 'Elite Hydration. Matte Finish. For the man who operates without excuses.',
    price: 35,
    image: 'https://www.zaddyproducts.com/cdn/shop/files/2_1000x.jpg?v=1751254417',
    vertical: 'skin',
    tag: 'Skin · Essentials',
    description: 'Apply it daily and move like you own the room. Clinical-grade, hormone-protective.',
  },
  {
    id: 'immortality-serum',
    name: 'Immortality • Stem-C Vitamin C Serum',
    benefit: 'Peptide-rich, brightening, anti-aging. Protect your edge.',
    price: 57,
    image: 'https://www.zaddyproducts.com/cdn/shop/files/Serum_new_bottle_1000x.jpg?v=1751427567',
    vertical: 'skin',
    tag: 'Skin · Essentials',
    description: 'Clinical authority meets dark luxury. Peptide-rich formula for deep cellular recovery.',
  },
  {
    id: 'ritual-cleanser',
    name: 'Ritual • Face & Beard Cleanser',
    benefit: 'Hemp oil base. Cleanse without compromise.',
    price: 28,
    image: 'https://www.zaddyproducts.com/cdn/shop/files/ZADDY_cleanser_220f0cb9-0f03-40e1-beaf-f8b46024470d_1000x.jpg?v=1751014136',
    vertical: 'skin',
    tag: 'Skin · Essentials',
    description: 'Hemp-infused cleanser that removes impurities while maintaining the skin\'s natural moisture barrier.',
  },
  {
    id: 'awaken-wash',
    name: 'AWAKEN • 2-in-1 Hair & Body Wash',
    benefit: 'Energizing formula. Clean ingredients. Sold Out.',
    price: 33,
    image: 'https://www.zaddyproducts.com/cdn/shop/files/Body_Wash_unisex_1000x.jpg?v=1752024730',
    vertical: 'skin',
    tag: 'Skin · ZEN•ERGY',
    description: 'Sold Out · Subscribe available. Energizing formula with clean ingredients.',
  },
  {
    id: 'ultimate-bundle',
    name: 'Zaddy Certified Bundle — Ultimate Edition',
    benefit: 'The complete system optimization. Maximum synergy.',
    price: 169,
    compareAtPrice: 188,
    image: 'https://www.zaddyproducts.com/cdn/shop/files/Zaddy_Set_Bundle_new_1000x.jpg?v=1751427349',
    vertical: 'skin',
    tag: 'Bundle',
    description: 'The complete Zaddy experience. Includes Subscribe & Save (saves additional 8%). SKU: ZBUN175',
  },
  {
    id: 'beard-bundle',
    name: 'Zaddy Certified Bundle — Beard Edition',
    benefit: 'Forged oil + Ritual cleanser + Hydra+. Precision grooming.',
    price: 117,
    compareAtPrice: 131,
    image: 'https://www.zaddyproducts.com/cdn/shop/files/bundle_beard_1000x.jpg?v=1750995640',
    vertical: 'skin',
    tag: 'Bundle',
    description: 'SKU: ZEB-B. Precision grooming for the modern man.',
  },
  {
    id: 'beard-free-bundle',
    name: 'Zaddy Certified Bundle — Beard-Free Edition',
    benefit: 'Hydra+ + Ritual cleanser + Immortality serum.',
    price: 111,
    compareAtPrice: 124,
    image: 'https://www.zaddyproducts.com/cdn/shop/files/bundle_nobeard_1000x.jpg?v=1750995559',
    vertical: 'skin',
    tag: 'Bundle',
    description: 'SKU: ZEB-NB. Complete skin optimization without the beard focus.',
  },
  {
    id: 'bde-briefs',
    name: 'B.D.E. Sports Briefs — Two Pack',
    benefit: 'Bold. Dominant. Effortless. High-stretch, second-skin fit.',
    price: 38,
    image: 'https://www.zaddyproducts.com/cdn/shop/files/IMG_4098_1000x.jpg?v=1746910966',
    vertical: 'apparel',
    tag: 'Apparel',
    description: 'Confidence starts with comfort. From the gym to the bedroom. Bold. Dominant. Effortless.',
  }
];

export const NAVIGATION = [
  { name: 'Skin', href: '#skin' },
  { name: 'Apparel', href: '#apparel' },
  { name: 'Health', href: '#health' },
  { name: 'About', href: '#about' },
];
